# Generated by Django 5.2.14 on 2026-05-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocr_engine", "0001_initial"),
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrresult",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocr_result",
                to="processing.job",
            ),
        ),
    ]
