# Generated by Django 5.2.14 on 2026-05-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_format", models.CharField(max_length=16)),
                ("target_format", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "input_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_jobs_as_input",
                        to="files.uploadedfile",
                    ),
                ),
                (
                    "output_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_jobs_as_output",
                        to="files.uploadedfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion Job",
                "verbose_name_plural": "Conversion Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
